name: Deploy using Docker Compose

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    env:
      DOCKER_CONFIG: /Users/jimmy_only/.docker-gh-actions
    steps:
      - name: Unlock login keychain for Docker
        env:
          MACOS_LOGIN_PASSWORD: ${{ secrets.MACOS_LOGIN_PASSWORD }}
        run: |
          security -v unlock-keychain -p "$MACOS_LOGIN_PASSWORD" ~/Library/Keychains/login.keychain-db
        
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop running containers
        run: docker-compose down || true

      - name: Rebuild images
        run: docker-compose build 

      - name: Start services
        run: docker-compose up

      - name: Show running containers
        run: docker ps
